# Generated by Django 3.1.2 on 2021-05-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(default='PATENTE', max_length=9)),
                ('marca', models.CharField(default='MARCA', max_length=100)),
                ('modelo', models.CharField(default='MODELO', max_length=100)),
                ('color', models.CharField(default='COLOR', max_length=100)),
                ('crearted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='RUT', max_length=11)),
                ('nombre', models.CharField(default='NOMBRE', max_length=100)),
                ('apellido', models.CharField(default='APELLIDO', max_length=100)),
                ('fono', models.CharField(default='FONO', max_length=100)),
                ('crearted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.vehiculo')),
            ],
            options={
                'db_table': 'Conductor',
            },
        ),
    ]
