# Generated by Django 3.1.2 on 2021-05-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crud.estado'),
        ),
    ]
